// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MakeReady.Data.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b4bc3351-f112-4195-b4f2-41baaf79a334"), entityTypeCount: 14)
        {
        }

        partial void Initialize()
        {
            var ammo = AmmoEntityType.Create(this);
            var firearm = FirearmEntityType.Create(this);
            var firearmMalfunction = FirearmMalfunctionEntityType.Create(this);
            var hitFactorSession = HitFactorSessionEntityType.Create(this);
            var hitFactorStage = HitFactorStageEntityType.Create(this);
            var magazine = MagazineEntityType.Create(this);
            var magazineMalfunction = MagazineMalfunctionEntityType.Create(this);
            var magazineModification = MagazineModificationEntityType.Create(this);
            var maintenanceLog = MaintenanceLogEntityType.Create(this);
            var maintenanceLogPart = MaintenanceLogPartEntityType.Create(this);
            var maintenancePart = MaintenancePartEntityType.Create(this);
            var maintenanceSchedule = MaintenanceScheduleEntityType.Create(this);
            var modification = ModificationEntityType.Create(this);
            var roundSession = RoundSessionEntityType.Create(this);

            FirearmMalfunctionEntityType.CreateForeignKey1(firearmMalfunction, ammo);
            FirearmMalfunctionEntityType.CreateForeignKey2(firearmMalfunction, firearm);
            HitFactorSessionEntityType.CreateForeignKey1(hitFactorSession, firearm);
            HitFactorStageEntityType.CreateForeignKey1(hitFactorStage, hitFactorSession);
            MagazineEntityType.CreateForeignKey1(magazine, firearm);
            MagazineMalfunctionEntityType.CreateForeignKey1(magazineMalfunction, ammo);
            MagazineMalfunctionEntityType.CreateForeignKey2(magazineMalfunction, magazine);
            MagazineModificationEntityType.CreateForeignKey1(magazineModification, magazine);
            MaintenanceLogEntityType.CreateForeignKey1(maintenanceLog, firearm);
            MaintenanceLogPartEntityType.CreateForeignKey1(maintenanceLogPart, maintenanceLog);
            MaintenancePartEntityType.CreateForeignKey1(maintenancePart, firearm);
            MaintenanceScheduleEntityType.CreateForeignKey1(maintenanceSchedule, firearm);
            ModificationEntityType.CreateForeignKey1(modification, firearm);
            RoundSessionEntityType.CreateForeignKey1(roundSession, ammo);
            RoundSessionEntityType.CreateForeignKey2(roundSession, firearm);
            RoundSessionEntityType.CreateForeignKey3(roundSession, magazine);

            AmmoEntityType.CreateAnnotations(ammo);
            FirearmEntityType.CreateAnnotations(firearm);
            FirearmMalfunctionEntityType.CreateAnnotations(firearmMalfunction);
            HitFactorSessionEntityType.CreateAnnotations(hitFactorSession);
            HitFactorStageEntityType.CreateAnnotations(hitFactorStage);
            MagazineEntityType.CreateAnnotations(magazine);
            MagazineMalfunctionEntityType.CreateAnnotations(magazineMalfunction);
            MagazineModificationEntityType.CreateAnnotations(magazineModification);
            MaintenanceLogEntityType.CreateAnnotations(maintenanceLog);
            MaintenanceLogPartEntityType.CreateAnnotations(maintenanceLogPart);
            MaintenancePartEntityType.CreateAnnotations(maintenancePart);
            MaintenanceScheduleEntityType.CreateAnnotations(maintenanceSchedule);
            ModificationEntityType.CreateAnnotations(modification);
            RoundSessionEntityType.CreateAnnotations(roundSession);

            AddAnnotation("ProductVersion", "9.0.6");
        }
    }
}
